### ISSUE TITLE
Wrong Variable name when using puppet as package provider

### ISSUE THREAD

**Issue by dionysius** [ctf/puppet-pbis#2]
Variable name is wrong. Follows a tiny fix. Otherwise you get following error:
"Error: Failed to apply catalog: Could not find dependency File[/opt/pbis-open] for Package[pbis-open] at /etc/puppet/modules/pbis/manifests/init.pp:44"

**Comment by benwebber** [comment]
Thanks, this is a silly mistake.

Can you reopen this as a pull request?
